### ISSUE TITLE
Fails with latin1 encoded files

### ISSUE THREAD

**Issue by osa1** [elaforge/fast-tags#11]
```
➜  ghc git:(master) ✗ fast-tags **/*.hs **/*.hsc **/*.lhs
exception reading "libraries/hoopl/prototypes/Cunning3.hs": libraries/hoopl/prototypes/Cunning3.hs: hGetContents: invalid argument (invalid byte sequence)
```

This file is encoded as `latin1`. I haven't tried files with other encodings. Note that `hasktags` indexes tags in that file just fine.

**Comment by elaforge** [comment]
Indeed, I think this was a known issue but I never got around to fixing it.  You could argue that the correct this is to fix the file since a file in an unknown encoding means you have no way to know what the identifiers are.  But if it's just in the comments like in Cunning3.hs, it's harmless to decode leniently, so that's what I did.  Should be fixed in the newest version.
