### ISSUE TITLE
Doesn't do qualified Imports properly

### ISSUE THREAD

**Issue by JonnyRa** [elaforge/fast-tags#33]
So using your suggested iskeyword mapping gets confused in cases like this:

where the name is the same

```
import qualified A.B.TheSnippet as Snippet

getStuff :: AType -> [Text]
getStuff= Snippet.getStuff. _snippet
         cursor here        ^
```
and without that mapping it just goes to the type declaration on the line above

I've anonomised some stuff a bit there but it should still make sense.

I wonder if a good way to do it would be to read qualified import statements and generate prefixes for the stuff in each module based on them.

Is that something which would be plausible?  I'm not familiar with how tags programs work.

I'd be up for taking a stab at it if so

**Comment by elaforge** [comment]
Yeah, qualified mode assumes you don't rename the module when you import it.

If you make fast-tags clever about import renames, then won't you wind up with a lot of ambiguous tags?  Lots of people shorten to one letter, and it would be common for the same letter to mean different things in different modules.  You'd have to be able to scope tags to a single file, where each file would have its own set of tags.  Maybe vim can actually do that, but then you go from one tags file to hundreds of them.

I've thought of something like this, but I came from the direction of trying to make vim smarter.  So tags would always be qualified by the complete module name, and vim would then look at the import block and try prefixing the tag if it found a matching import line.  This would make searching for unqualified names smarter too, because it could prioritize ones from imported modules.

Unfortunately I can't even figure out how to get vim to do simple things let alone complicated ones. 
 E.g., the set iskeyword stuff in the vimrc is broken because it restores iskeyword after switching files.  I actually use a more complicated version, which is also broken in a more complicated way.

**Comment by JonnyRa** [comment]
Haha, sounds about right for vim!  Unfortunately I've not got any experience writing plugins for it, just reading a few + doing stuff in my vimrc.

We have some naming like that in our code, I feel like it shouldn't be too bad for ambiguity though unless you already have a lot of duplicate names - say if you had module `horse` and function `chew`.  And you imported it in a few different places unqualified, as `Horse` and as `H` then unless you also had another function 'chew' somewhere else none of them would be ambiguous and the more qualified ones would be less likely to clash anyway (eg they're only likely if you had Human chew or something - as you might get the single letters clashing but wouldn't get the fuller qualifications clashing).  So I think you'd still be able to just have one file but you'd just have a few entries that all pointed to the same thing - eg Horse.chew H.chew and chew all going to the same place.

I don't know if other languages have the same sort of naming problem, might be other people have solved this problem for a different language.  I think one of the other haskell tagging things claims to do something clever with imports, I haven't tried it though and can't remember which one off hand!

You could have the iskeyword thing set up as an autocommand on buf enter or something presumably?

**Comment by JonnyRa** [comment]
http://hackage.haskell.org/package/hothasktags is the one I was thinking about

**Comment by elaforge** [comment]
Oh I see what hothasktags does.  If you do `module Z where import A as B` then it will add all tags from A with a `B.` prefix, but put a `file:Z.hs` on them.  vim says it gives file:% lines priority, so presumably if you look for B.a inside Z.hs it won't get confused with all the B.a tags in other files.

So I think the answer to my question about "you'd have to be able to scope tags to a single file" is yes, vim actually can do that.

It seems this might get tricky with fast-tags wanting to be incremental though.  Say you add a new import line, now it has to go find that module, and copy all of its exports.  Maybe not so bad... collect import lines and do a recursive tags run for each one.

This sounds feasible, and it solves a real problem, so if you're willing to give it a shot I say go for it.  I still think having vim look at the import lines and modify its tag search accordingly is more elegant because it doesn't multiply the size of the tags file by the number of import lines in each module.  My tags file  is "only" 3k lines and 1.4mb, and with an average of 15 imports per file, that implies 45k lines and 21mb.  Binary search should still be plenty fast, and reading and writing a 21mb file is basically instant nowadays too, so maybe it's nothing to worry about.

That said, improving vim's ^] could also solve the iskeyword problem.  I think I want to not change iskeyword at all, since resetting it is so error prone.  It should be possible to replace ^] with a function that reads the cursor position, expands the word, and tries several variants.  And once you are at that point, it shouldn't be much harder to grope around at the front of the file for `^import (...) as (...)`.  It's just that you'd probably have to write that in vimscript (ugh) or python (I think most vims come with that compiled in now?).

It's up to you!  I just ask that if you do the pure tags solution, put it behind a flag so we can opt in.

**Comment by elaforge** [comment]
Inspired by this conversation, I added qualified_tag.py, to fix this iskeyword problem.  This is the thing that could be extended to look in the imports list, but I haven't done that yet.

**Comment by elaforge** [comment]
I couldn't leave it halfway, so I went ahead and implemented the "go look at the import block".  I think this should fix the problem.  I'm going to use it for a while to see how it works.

Of course, this doesn't solve the problem for people without python in their vim, or for emacs, so there still might be room for the file: static tags version.  I think this will work for me though, so I'll leave it to you if this will fix your situation.  If you have vim +python, give it a try and let me know how it works.

**Comment by JonnyRa** [comment]
That's awesome! yeah that sounds like a better solution.  I'll give it a whirl.  Just having a quick look over what you've done and I think you should be able to improve it by using `<cword>` in your mapping:  something like this:

     nmap  <c-]> :py qualified_tag.tag_word(vim)<cr>

to this:     

     nnoremap <silent> <C-]> :execute "py qualified_tag.tag_word(vim," .expand('<cword>'). ")"<cr> 

Execute is basically eval on the string, `.` is string concatenation, `<cword>` gets the word under the cursor and expand basically just makes that work! (I've fiddled around with `<cword>` quite a lot before and 90% of the time you need to use exec and expand to make it work!)

I'd also use nnoremap aswell just on general principles although it shouldn't make any difference there anyway.

That way you could do away with the stuff that you put all the warning comments on.

**Comment by elaforge** [comment]
`<cword>` uses iskeyword, and the whole point of the expand_word stuff is to get a word expansion that doesn't use `<cword>`.  If `<cword>` were good enough then we can just use the built-in ^].

Another approach would be to define a "text object" which uses the proper haskell-ish rules, then it would also work with the usual vi operators, and I'm sure there are plenty of ways to get the custom text object under the cursor.  I looked into it a bit and gave up... maybe it was complicated and poorly documented?  Don't remember.

nnoremap is generally safer though, so I'll use that.

**Comment by JonnyRa** [comment]
Haha, didn't realise that!  Thought you'd missed something obvious when it was the other way around!  Yeah that sounds like a bit of a hassle, this approach seems fine, especially if you set it up as autocommand on haskell filetype (so `C-]` still works for other stuff (it's really useful in the help files in particular))... something like:

```
augroup fast-tags
autocmd! fast-tags
autocmd FileType haskell nnoremap <buffer> nnoremap ....
augroup END
```

the command group is there so it doesn't get duplicated every time you source...

**Comment by elaforge** [comment]
Right, I was assuming the user would properly divide up the global initialization and the *.hs specific parts.  I didn't put it in because everyone probably does it in a different way, or at least differently from how I do it.  I don't use filetype, for instance, so that wouldn't work for me.

I'll put in some notes about it just to be clear.

<buffer>'s good too, thanks for showing me that.  There's an endless supply of little doodads to learn about vim.

If this has solved the problem for you, feel free to close the issue.  If this works for me with no problems for a month or so I'll do a new hackage version.

**Comment by JonnyRa** [comment]
I'll try and give it a go some time this week.  I just did a `stack install fast-tags` to get it initially, would I need to pull the repository and build?  Is it as simple as just doing a stack install when I've pulled?  I'm fairly new to haskell still

**Comment by elaforge** [comment]
I don't know anything about stack, but you definitely have to build from github since I haven't updated hackage yet.  Something like:

`git pull ...; cd fast-tags; cabal configure; cabal install`

**Comment by JonnyRa** [comment]
Just tested now. that's done the trick  Nice one!  I'll let you know if I run into any issues

**Comment by JonnyRa** [comment]
Ok so I realised I hadn't actually swapped to using the python thing!  I'm getting the error message `unrecognized option `--fully-qualified'` after doing a cabal install.  I'm not familiar with using cabal on it's own but `where fast-tags` tells me it coming from `~/.local/bin/fast-tags`.  Is that where cabal installs stuff to?

Also I'm on a version of vim with python3.  I had a couple of minor tweaks to get it to work, can submit them in a pull request if you want?

**Comment by elaforge** [comment]
It's probably because it's --fully_qualified with an underscore.  But now that you mention it, it's inconsistent with the other flags.  I'll change that.

Sure, go ahead and send python3 patches.  I thought that was separately configured on vim via :py3 though.  If you do :version, do you see -python +python3?  And :py print('hi') works?  It doesn't require :py3 print('hi')?

**Comment by JonnyRa** [comment]
I thought it said with a `-` in the python file but you're right it says `_`.  Also related is that it doesn't report the new flag on the command line.

Yeah that's what I get in version.

In Vim It's basically changing anything with `:py..` calls into `pyx..` to work with either 2 or 3 and then in the python was just replacing a couple of `print blah` calls with `print (blah)`... I'm not a python person (although it was the first language I learnt at uni!) but from the reading I did it sounds like that form of print works for both 2 and 3.  Apparently some more complex cases need something like `import from __future__ print function`.  I don't think that's needed here though

**Comment by JonnyRa** [comment]
Actually I can't get it with the underscore either

**Comment by elaforge** [comment]
If you just did git pull then it's now hyphen.  Whatever it is, you'll see it in --help.

The other thing I can think of is that you're being shadowed by some other version.  Usually cabal installs in ~/.cabal, not ~/.local.

**Comment by JonnyRa** [comment]
Speedy!  No I've not pulled yet. ok, that makes sense... I'll check my path and maybe delete the one in local.

**Comment by JonnyRa** [comment]
Got it the new version now but I'm running into a problem with the tag generation.

I just tried going to a qualified tag and it failed... searching for the function name in the list of tags (using the fzf plugin) I can see it's making the fully-qualified tags from the repository root (where I have my vim cd set to).

The code I'm working on has a repository root with lots of different projects/packages in it so the folder structure is like:

`package-name/src/Namespace/Is/Here.hs`
which is resulting in tags like
`package-name.src.Namespace.Is.Here.functionName`

whereas the namespaces/module names referred to in code will just be the 
`Namespace.Is.Here` part.

From the error message it seems to be correctly making the fully qualified name to query the tags.

Not sure what a good approach is... could possibly search for the tag as a prefix of generated ones...,. or slightly hacky could recognise `src` as a package root.  I'm not sure if that's a stack thing or just a more general convention...

actually thinking about it, it should be possible to parse the correct names out of each module declaration in the files?

**Comment by elaforge** [comment]
Support for multiple roots is a whole other feature, so let's put that in a different issue.  I'll copy paste your comments over.
