### ISSUE TITLE
travis broken for 8.4.1

### ISSUE THREAD

**Issue by elaforge** [elaforge/fast-tags#36]
This is just to document that it's a known issue.

I don't really understand it though, it seems like cabal new-build is trying to install alex, even though cabal never installed tool dependencies before, and then it's getting a version mismatch, which alex shouldn't have.  But it's annoying to debug because cabal-install itself doesn't build on 8.4.1.

**Comment by sergv** [comment]
I think cabal installs `alex` because it's not in the PATH. I can try to make a PR that fixes that.

Actually, is there a reason to drop GHC 7? Since no new features are actually used, I think it's a good idea to maintain backwards compatibility so that the tool will be usable with any GHC version. Even though I don't use older version myself, I'm aware of large-scale industry Haskell users that use `7.8.4` and, for better or worse, are going to stick wit hit in foreseeable future.

**Comment by sergv** [comment]
Actually no, disregard my previous explanation. The `cabal new-build` has fixed its tracking of dependencies and now always builds all of the tools, even when they're present in PATH. I believe the reason for that is complete nix-style reproducibility - even if you have `alex` in PATH, it may not be equivalent to the one built from scratch.
