### ISSUE TITLE
CPP issues

### ISSUE THREAD

**Issue by sjakobi** [elaforge/fast-tags#48]
When I run `fast-tags` on [this file](https://github.com/dhall-lang/dhall-haskell/blob/cb38ba294172fb0a4d5f663c56318ff19bad1b03/dhall/src/Dhall/Parser.hs), it seems unable to produce tags for everything that comes after some rather innocuous CPP starting on line 47:

```
!_TAG_FILE_SORTED	1	//
ParseError	dhall/src/Dhall/Parser.hs	46;"	t
Parser	dhall/src/Dhall/Parser.hs	6;"	m
expr	dhall/src/Dhall/Parser.hs	37;"	f
exprA	dhall/src/Dhall/Parser.hs	42;"	f
```

I wonder whether `fast-tags` could do better here?

**Comment by elaforge** [comment]
fast-tags doesn't process CPP, it just ignores lines starting with # and hopes things work out.  It's not even that smart about CPP, it just assumes any line with # in the first columns must be CPP... originally this was because I wanted it to work on *.hsc files, which are not CPP but kind of look like it.

In this case, it looks like it gets confused by the unbalanced open braces.

1. The principled solution would probably be to run the file through CPP first.  I can't do it unconditionally because CPP gets mad at haskell string-gap syntax, so I could check for LANGUAGE CPP.  That's not guaranteed to be right since the flag could be in the cabal file or other build spot, but I'm ok with forcing people to add the pragma.  Of course it's slower but I think CPP is pretty fast.  Maybe cpphs doesn't have the string-gap problem?

2. The practical solution is to just send a PR to change Parser.hs to put the { before the #if line.  That's what I would do anyway, since the unbalanced braces confuse editors too.

I advise 2 for now because it's less work for me.  If it turns out there are a lot of problems with the simple-minded approach to CPP then I'd consider 1.

**Comment by sjakobi** [comment]
Thank you for the diagnosis and explanation, @elaforge. I went with option 2!
